### ISSUE TITLE
error when called from indexer.php --clear

### ISSUE THREAD

**Issue by Spockie** [LarsGit223/dokuwiki-plugin-randominc#13]
sudo -u apache /usr/bin/php /var/www/html/dokuwiki/bin/indexer.php --clear
...
sidebar... Indexer: finished
done.
start... ☠ Error: Call to a member function getUserData() on null in /var/www/html/dokuwiki/lib/plugins/randominc/syntax.php:225
Stack trace:
#0 /var/www/html/dokuwiki/lib/plugins/randominc/syntax.php(96): syntax_plugin_randominc->_applyMacro(':dyk')
#1 /var/www/html/dokuwiki/inc/parser/renderer.php(111): syntax_plugin_randominc->render('metadata', Object(Doku_Renderer_metadata), Array)
#2 /var/www/html/dokuwiki/inc/parserutils.php(497): Doku_Renderer->plugin('randominc', Array, 5, '{{randomincsec>...')
#3 /var/www/html/dokuwiki/inc/parserutils.php(272): p_render_metadata('start', Array)
#4 /var/www/html/dokuwiki/inc/indexer.php(1392): p_get_metadata('start', 'internal index', 4)
#5 /var/www/html/dokuwiki/bin/indexer.php(82): idx_addPage('start', true, true)
#6 /var/www/html/dokuwiki/bin/indexer.php(71): IndexerCLI->index('start')
#7 /var/www/html/dokuwiki/bin/indexer.php(57): IndexerCLI->update()
#8 /var/www/html/dokuwiki/vendor/splitbrain/php-cli/src/CLI.php(131): IndexerCLI->main(Object(splitbrain\phpcli\Options))
#9 /var/www/html/dokuwiki/bin/indexer.php(107): splitbrain\phpcli\CLI->run()
#10 {main}

**Comment by lpaulsen93** [comment]
@Spockie Thanks for reporting the issue. This is fixed now in current master branch.
