### ISSUE TITLE
Suggestion for an additional option

### ISSUE THREAD

**Issue by diltigug** [LarsGit223/dokuwiki-plugin-randominc#2]
Hello LarsGit223,

```
Thank you for adopting the plugin. It works perfectly, except for a small thing:

For me the date under the random side is not formatted correctly. 
It looks like this: %2017%04%26%09:%Apr
```
Edit 20.06.17, date problem move to [https://github.com/LarsGit223/dokuwiki-plugin-randominc/issues/3](url)

And a wish / suggestion for an additional option, I would also have:

It would be great if you could display the headline of the random page as a link to this page.
From the principle, like the "readmore" feature in the blog plugin of Dokufreaks. [https://www.dokuwiki.org/plugin:blog](url)
Would be great if this is feasible.
Greetings,
diltigug

**Comment by lpaulsen93** [comment]
Could you please post the date problem in another issue. I would consider the date format as an potential bug and the option is a feature request. That are two things and both should have their own issues entry. Thanks!

**Comment by diltigug** [comment]
Done.

Is it okay in this form?

**Comment by lpaulsen93** [comment]
:thumbsup: Thanks.

**Comment by lpaulsen93** [comment]
The plugin is now directly calling the include plugin. So you can use all include plugin flags. Adding the flag ```&link``` will render your first heading as a link.

The randominc specific flags ```max-width``` and ```max-height``` are still supported.

Please test. If your test's are fine I will publish a new release.

**Comment by diltigug** [comment]
Great, a quick test and it works. The heading is shown as a link. Thank you.
