### ISSUE TITLE
Documentation Doesn't Make Requirements Clear

### ISSUE THREAD

**Issue by nephatrine** [LarsGit223/dokuwiki-plugin-randominc#5]
Was getting a PHP error and HTTP 500 whenever trying to use this plugin. Plugin page says it is "dervied from" the Include plugin, but it appears to actually require the Include plugin to function. The documentation should be made more clear I think that the Include plugin needs to be installed.

**Comment by lpaulsen93** [comment]
Oops, my fault, I am sorry for the hassle. After adopting the plugin from the previous author I changed it. To be able to use all the features of the include plugin and to get rid of code duplication, I made it call the include plugin directly. Unfortunately I forgot to change the documentation.

Just updated the plugin page so this can be closed. Thanks for reporting the issue.
