### ISSUE TITLE
 Fatal error: Call to a member function..

### ISSUE THREAD

**Issue by casperklein** [LarsGit223/dokuwiki-plugin-randominc#6]
Dokuwiki Version: 2017-02-19e "Frusterick Manners"

I just installed dokuwiki-plugin-randominc, but I can't get it to work.

When I use for example ```{{randominc>bash}}``` on a page, the following error is thrown:

```Fatal error: Call to a member function get_flags() on null in /doku/lib/plugins/randominc/syntax.php on line 127```

fyi: I haven't changed the default settings of the plugin in the admin panel.

**Comment by lpaulsen93** [comment]
Please install the include plugin and re-try.

**Comment by casperklein** [comment]
My fault. I overread ```This plugin uses the include plugin and therefore it requires the include plugin to be installed.```

Works now!

Maybe you could consider, adding a little check, if include plugin is installed. In my case, it was not possible to edit the page after saving, because of the fatal error. I had to edit the page on file system level.

**Comment by lpaulsen93** [comment]
> Maybe you could consider, adding a little check...

Yes, the missing check is my fault. I will add a check soon.

**Comment by lpaulsen93** [comment]
I have added an error message now, see commit 1b2535e565e4f4a4d99a883777b662feb568842a.
