### ISSUE TITLE
depth/recursion option [Feature Request]

### ISSUE THREAD

**Issue by nephatrine** [LarsGit223/dokuwiki-plugin-randominc#7]
Would love a &depth=# option (exactly like the Include plugin has for the namespace includes). It seems randominc recurses through namespaces under the one specified by default. I'd at least like an option on whether to include pages in those sub-namespaces or not. I'm doing some really complicated stuff at the moment with this plugin (random character creation for a tabletop RPG) and this would let me streamline a few things.

**Comment by lpaulsen93** [comment]
Please have a look at the randominc plugin page:

> Additional Flags
> 
> From release 2017-08-04 on, the Random Include plugin also supports all flags which are supported by the Include Plugin. E.g. {{randominc>:playground:test&link}} would make the first heading of the included page be rendered as a link.
> 

So all flags that work for the include plugin should also work for the randominc plugin. Have you tried it?

**Comment by nephatrine** [comment]
Yes, I have tried. I think the issue is that the flag is from the **namespace** syntax of the Include plugin rather than the **page** or **section** syntax. Per the dokuwiki plugin page:

> randominc works as page syntax of Include Plugin.
> randomincsec should work as section syntax.

Since randominc is picking a page from a namespace though, it would make a lot of sense I think to include some of the namespace syntax like support ``&depth=1`` at least.

**Comment by lpaulsen93** [comment]
Yes, you are right.

The randominc plugin includes a random page and that cannot be done with the include plugin directly. So it first scans the namespace to build itself a list of available pages and then picks a random page from that list. It is then displayed using the include plugin.

The good news is that the randominc plugin uses the standard/core DokuWiki functions ```seach``` and ```search_allpages``` to scan for the pages. They support a ```depth``` option.

The current master version of the randominc plugin uses that depth option. Just specify the flag, e.g. ```depth=1``` to limit the directory/namespace search depth. If the flag is missing, than there is no limit (as before).

Please test and give some feedback.

**Comment by lpaulsen93** [comment]
I have just increased the version, so the new option is now officialy released. Therefore I close this now.
